spring:
  application:
    name: application-service
  mvc:
    servlet:
      path: /application-service

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

database:
  hibernate:
#    Local DB connection:
#    url: jdbc:mysql://localhost:3306/application
#    username: root
#    password: Sally248qq_
#    AWS RDS connection:
    url: jdbc:mysql://db-hr-team3.cx2wy5qjzske.us-west-1.rds.amazonaws.com:3306/application
    username: admin
    password: 12345678
    driver: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5Dialect
    showsql: true
    hbm2ddl:
      auto: update